# Generated by Django 4.1.7 on 2023-07-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
    ]
